version: '3.8'

services:
  next:
    build:
      context: ../../
      dockerfile: .docker/development/Dockerfile
    image: next_dev
    container_name: next_dev
    command: yarn dev
    volumes:
      - ../../:/next-app
    ports:
      - "3000:3000"
