version: '3.8'

services:
  next:
    build:
      context: ../../
      dockerfile: .docker/production/Dockerfile
    image: next_prod
    container_name: next_prod
    command: node /app/server.js
    user: nextjs
    volumes:
      - .:/next-app
    ports:
      - "3000:3000"
